### ISSUE TITLE
关于断网及多次重复点击按钮情况的讨论

### ISSUE THREAD

**Issue by yang12318** [NicoNicoishare/ishare_android#15]
因为在对人进行关注以及取消关注 或对动态进行点赞收藏/取消点赞收藏时存在网络卡顿、断网等多种情况，同时用户可能短时间内重复点击同一按钮，这会带来一些麻烦，需要列举一些用户使用情况进行测试修改

**Comment by youxiho1** [comment]
或许我们不需要考虑用户的使用情况，直接就在用户点击了一次之后把按钮禁掉，不让他再多次点击了？但是这样做是不是不太合理？

**Comment by youxiho1** [comment]
我们可以考虑4次左右的连续点击的全部情况，每一次点击的结果会分为断网、网速慢、网速正常（指在下一次点击之前能够在服务器端完成这次操作），然后我们列一个表格讨论一下这些情况？

不是单纯的枚举，很多情况是可以合并的，实际列举的工作量没有想象中那么大（笑哭

（每增加一次都会使需要讨论的情况指数级增长，我觉得讨论4次左右就可以了？）

在讨论完这些情况之后，我们就可以根据我们列出的这个表格进行编码了？

**Comment by yang12318** [comment]
> 或许我们不需要考虑用户的使用情况，直接就在用户点击了一次之后把按钮禁掉，不让他再多次点击了？但是这样做是不是不太合理？

这样不合理，发送时可采用，其余不行

**Comment by yang12318** [comment]
> 我们可以考虑4次左右的连续点击的全部情况，每一次点击的结果会分为断网、网速慢、网速正常（指在下一次点击之前能够在服务器端完成这次操作），然后我们列一个表格讨论一下这些情况？
> 不是单纯的枚举，很多情况是可以合并的，实际列举的工作量没有想象中那么大（笑哭
> （每增加一次都会使需要讨论的情况指数级增长，我觉得讨论4次左右就可以了？）
> 在讨论完这些情况之后，我们就可以根据我们列出的这个表格进行编码了？

可以

**Comment by youxiho1** [comment]
> > 我们可以考虑4次左右的连续点击的全部情况，每一次点击的结果会分为断网、网速慢、网速正常（指在下一次点击之前能够在服务器端完成这次操作），然后我们列一个表格讨论一下这些情况？
> > 不是单纯的枚举，很多情况是可以合并的，实际列举的工作量没有想象中那么大（笑哭
> > （每增加一次都会使需要讨论的情况指数级增长，我觉得讨论4次左右就可以了？）
> > 在讨论完这些情况之后，我们就可以根据我们列出的这个表格进行编码了？
> 
> 可以

那么我们就综合这两种情况，在发送动态的时候我们在点击发送按钮之后把这个按钮暂时禁止掉；其他的按钮我们按照我们的表格来进行分情况讨论
