### ISSUE TITLE
关于页多样式列表问题

### ISSUE THREAD

**Issue by yang12318** [NicoNicoishare/ishare_android#18]
因为关于页设计多个样式列表，需要合并成一个列表但仍保留原有样式，是否有好用的adapter等对此进行适配

**Comment by youxiho1** [comment]
我们所有Recyclerview都使用BRVAH去做，然后我们所有下拉刷新上拉加载都使用EasyLayout去做

这样的话，我们在解析接口的时候是可以判断出来这一条消息的类型的，这里我们把这一类型称为一个整型变量type，接下来我们只需要判断这个type的值，就可以在Adapter中区分出来我们要加载一条什么样的item进来，也同时决定了我们页面渲染时按照什么样的方式渲染

这样可行吗
