### ISSUE TITLE
Fragment之间传值

### ISSUE THREAD

**Issue by youxiho1** [NicoNicoishare/ishare_android#22]
搜索页的结构如下：
搜索框+TabLayout，其中TabLayout中有两个Fragment（SearchUserFragment和SearchDynamicFragment），搜索框中的值要怎么传递到SearchUserFragment以及SearchDynamicFragment中呢？并且点击搜索按钮和滑动ViewPager的时候，都应该刷新Fragment中展示的内容吗？
（以下问题待思考：快速滑动ViewPager时会发生什么呢？点击搜索按钮之后快速滑动ViewPager时会发生什么呢？）
主问题是：解决SearchFragment和SearchUserFragment以及SearchDynamincFragment之间传参的问题
其他问题是：解决该页面可能会出现的各种各样的潜在bug

**Comment by yang12318** [comment]
最终对搜索页重新设计，以此解决问题
