### ISSUE TITLE
评论测试bug

### ISSUE THREAD

**Issue by yang12318** [NicoNicoishare/ishare_android#27]
添加评论后，向上拉动刷新，评论条数不变，动态不显示新的，关掉软件重进可正常显示

**Comment by youxiho1** [comment]
你指的是 添加评论后回到动态页面进行向上拉动刷新，然后出现后面这些bug是吗

**Comment by yang12318** [comment]
> 你指的是 添加评论后回到动态页面进行向上拉动刷新，然后出现后面这些bug是吗

是的

**Comment by youxiho1** [comment]
> > 你指的是 添加评论后回到动态页面进行向上拉动刷新，然后出现后面这些bug是吗
> 
> 是的

报错页面是哪个Fragment呀？还是都有这个bug？
评论条数不变这个问题我想一想怎么解决好，似乎只能是监听onResume函数，然后在这个函数中调用一次refresh？
然后什么叫动态不显示新的呀？你是想描述这样的问题吗：
我9：00开始评论A动态，我的评论是第3条评论，然后9:10评论完成，按下返回键回到首页
在9:05 ktchen发送了一个动态，这个动态我们称为B
现在的这个bug是不是说：我回到首页之后A动态的评论数仍为2，并且首页中也没有B这个动态

我理解的对吗

**Comment by yang12318** [comment]
> 你指的是 添加评论后回到动态页面进行向上拉动刷新，然后出现后面这些bug是吗
> 
> 是的
> 
> 报错页面是哪个Fragment呀？还是都有这个bug？
> 评论条数不变这个问题我想一想怎么解决好，似乎只能是监听onResume函数，然后在这个函数中调用一次refresh？
> 然后什么叫动态不显示新的呀？你是想描述这样的问题吗：
> 我9：00开始评论A动态，我的评论是第3条评论，然后9:10评论完成，按下返回键回到首页
> 在9:05 ktchen发送了一个动态，这个动态我们称为B
> 现在的这个bug是不是说：我回到首页之后A动态的评论数仍为2，并且首页中也没有B这个动态
> 我理解的对吗

之前是在HomeHotFragment，其他页还未进行测试
你理解的没有问题

**Comment by youxiho1** [comment]
我们检查了微博等软件在这一功能上的实现，决定仿照其效果来实现（向业界最佳实践学习）
