### ISSUE TITLE
热门动态的Fragment未加入上拉加载功能

### ISSUE THREAD

**Issue by youxiho1** [NicoNicoishare/ishare_android#28]

**Comment by yang12318** [comment]
因为热门是后加页面，部分功能可能忘记加入，之后会进行补充

**Comment by yummyJade** [comment]
因在fragment中来回切换时RecyclerView获得了焦点，而RecyclerView的 focusableOnTouchMode属性默认是true，所以在切换时RecyclerView自动获得焦点就滚动到了底部，将RecyclerView上面的控件的设置android:focusableInTouchMode="true"即可

**Comment by youxiho1** [comment]
该bug已查，并已解决

出现bug原因为代码中误加入了setLoadMoreModal(NONE)一类的话（也就是说实际上热门动态这一页是做了上拉加载功能的，只不过因为这个设置问题让我们以为它没有）

p.s. 文本比对工具真好用
