### ISSUE TITLE
一些功能优化记录

### ISSUE THREAD

**Issue by yang12318** [NicoNicoishare/ishare_android#31]
1、删除热门页对应的空白页
2、关于页两个列表动画修改
3、关于我页面去除“我”对“我”的动态操作（如点赞、评论等）
4、搜索页未搜索前不应允许下拉刷新与下拉加载
5、上拉加载的toast与上拉加载显示过长
6、下拉刷新颜色太丑

**Comment by yang12318** [comment]
1. 搜索按钮点击后进行10s倒计时
2. 搜索页recyclerview在最开始加入一个被搜的人员
3. 发表动态时图片旋转90度的bug
4. 发表动态未发表成功时点击首页会致使程序崩溃
5. UserActivity待修改
6. 评论数待修改
7. 下拉刷新样式待修改
8. 所有页面的上拉加载的延迟时间修改成1秒
9. 上拉加载如果没有内容了不显示那个加载成功
10. 所有页面的snackbar的持续时间修改为1秒
11. 测试用户名和密码使用emoji是否会崩溃
12. 所有的Toast的getActivity/getContext都会因为在Toast发出之前切换Fragment崩溃

**Comment by youxiho1** [comment]
> 1、删除热门页对应的空白页
> 2、关于页两个列表动画修改
> 3、关于我页面去除“我”对“我”的动态操作（如点赞、评论等）
> 4、搜索页未搜索前不应允许下拉刷新与下拉加载
> 5、上拉加载的toast与上拉加载显示过长
> 6、下拉刷新颜色太丑

1、 已删除
2、 已修改，待检查 @yang12318 
3、 已去除
4、 已禁止
5、 已加入新TODO list
6、 已加入新TODO list

**Comment by youxiho1** [comment]
1. 搜索页recyclerview在最开始加入一个被搜的人员
2. 发表动态时图片旋转90度的bug
3. 下拉刷新样式待修改
4. 测试用户名和密码使用emoji是否会崩溃
5. 所有的Toast的getActivity/getContext都会因为在Toast发出之前切换Fragment崩溃

**Comment by youxiho1** [comment]
1. 搜索页recyclerview在最开始加入一个被搜的人员（如果搜不到人则应隐藏这个view）
2. 发表动态时图片旋转90度的bug
3. 下拉刷新样式待修改
4. 测试用户名和密码使用emoji是否会崩溃
5. 所有的Toast的getActivity/getContext都会因为在Toast发出之前切换Fragment崩溃

**Comment by youxiho1** [comment]
> 1. 搜索页recyclerview在最开始加入一个被搜的人员（如果搜不到人则应隐藏这个view）
> 2. 发表动态时图片旋转90度的bug
> 3. 下拉刷新样式待修改
> 4. 测试用户名和密码使用emoji是否会崩溃
> 5. 所有的Toast的getActivity/getContext都会因为在Toast发出之前切换Fragment崩溃

4. 已测试，不会崩溃，可以正常使用emoji
5. 已修改
