### ISSUE TITLE
发送动态多图问题

### ISSUE THREAD

**Issue by yang12318** [NicoNicoishare/ishare_android#32]
场景描述：选择两张图片，点击分享后一直等待，在未成功发送之前点击首页，这时动态发送成功，但图片向右翻转了90°，不知是否可以复现

**Comment by youxiho1** [comment]
我这里的情况是：
按你描述的场景去执行，程序会直接崩溃
图片逆时针旋转90度是不定期发生的
我的测试结果是：这是2个不同的bug，不一定同时出现

**Comment by youxiho1** [comment]
已合并入最新的TODO list
